# Generated by Django 5.0.3 on 2024-04-24 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1_statistic', '0004_rename_answer_f1_user_score_question'),
        ('tips', '0005_f1_question_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='f1_user_score',
            name='question',
        ),
        migrations.AddField(
            model_name='f1_user_score',
            name='answer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tips.f1_answer'),
            preserve_default=False,
        ),
    ]
