# Generated by Django 5.0.2 on 2024-03-02 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='f1_season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('is_ended', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'f1_season',
            },
        ),
        migrations.CreateModel(
            name='f1_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'f1_team',
            },
        ),
        migrations.CreateModel(
            name='f1_race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.f1_season')),
            ],
            options={
                'db_table': 'f1_race',
            },
        ),
        migrations.CreateModel(
            name='f1_pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.f1_team')),
            ],
            options={
                'db_table': 'f1_pilot',
            },
        ),
    ]
