# Generated by Django 5.0.2 on 2024-03-02 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='language',
        ),
        migrations.AddField(
            model_name='user',
            name='language_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
