# Generated by Django 5.0.2 on 2024-03-02 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='f1_question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_number', models.BooleanField(default=False)),
                ('closest_number', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'f1_question',
            },
        ),
        migrations.CreateModel(
            name='f1_question_translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'f1_question_translation',
            },
        ),
        migrations.CreateModel(
            name='f1_race_result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'f1_race_result',
            },
        ),
        migrations.CreateModel(
            name='f1_answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.f1_race')),
            ],
            options={
                'db_table': 'f1_answer',
            },
        ),
    ]
