# Generated by Django 5.0.2 on 2024-03-02 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('details', '0001_initial'),
        ('tips', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='f1_answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='f1_answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tips.f1_question'),
        ),
        migrations.AddField(
            model_name='f1_question_translation',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.f1_language'),
        ),
        migrations.AddField(
            model_name='f1_question_translation',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tips.f1_question'),
        ),
        migrations.AddField(
            model_name='f1_race_result',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tips.f1_question'),
        ),
        migrations.AddField(
            model_name='f1_race_result',
            name='race',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='details.f1_race'),
        ),
    ]
