# Generated by Django 5.0.3 on 2024-04-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0004_alter_f1_race_result_race'),
    ]

    operations = [
        migrations.AddField(
            model_name='f1_question',
            name='group_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
